# docker-compose.yml
version: '3'

services:
  influxdb:
    image: 'influxdb:1.4'
    ports: ['8086:8086']
    environment:
      INFLUXDB_DB: twitch

  chronograf:
    image: 'chronograf:1.4'
    entrypoint: 'chronograf --influxdb-url=http://influxdb:8086'
    depends_on: ['influxdb']
    ports: ['8888:8888']
