# docker-compose.yml
version: '3'

services:
  influxdb:
    image: 'influxdb:1.4'
    ports: ['8086:8086']
    environment:
      INFLUXDB_DB: twitch

  chronograf:
    image: 'chronograf:1.4'
    entrypoint: 'chronograf --influxdb-url=http://influxdb:8086'
    depends_on: ['influxdb']
    ports: ['8888:8888']

  rabbit1:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
